### ISSUE TITLE
WoWSim - Rogue Settings not saving the Professions 

### ISSUE THREAD

**Issue by Rerox-WoW** [wowsims/wotlk#3126] opened 2023-05-30 07:29 UTC
In the local version of wowsim (V. 0.1.31) in the Rogue Sim, saving "Settings" does not save the selected Professions!
All other settings can be saved as expected.

**Comment by Rerox-WoW** [comment] 2023-06-29 16:07
Still present in the latest version v0.1.35 of the simulator (downloadable AND online) Professions are not saved under "Saved Settings"if you switch between different Settings for different charaacters. all other settings are saved, so this should be an easy fix to add those two fields to the save. Please?

**Comment by kayla-glick** [comment] 2023-08-23 02:45
Closing as a duplicate of https://github.com/wowsims/wotlk/issues/3522. This will be fixed in the next release though

**Closed by kayla-glick** 2023-08-23 02:45 UTC
Labels: bug, UI/UX
