### ISSUE TITLE
Socket and Enchant Lists are empty on Items-View

### ISSUE THREAD

**Issue by Machigatta** [wowsims/wotlk#3952] opened 2023-10-25 13:53 UTC
**Describe the bug**
The list of sockets and enchants are empty whenever i open at item to change the enchants or gems. If i click directly on a enchantment, where it opens the item directly in the enchantment tab-view, the list works fine. This occurs for me for both versions, localhost-version and the github.io-hosted version. It also seems to be a special kind of bug, since no one in my guild has the this issue. I checked the web-console there is also no js-error or anything showing.

**To Reproduce**
1. Go to any character 
2. Click on any item
3. Go to enchant or gems
4. No entries are there
5. Choose different entry in the Phase-Dropdrown / or in gems change the selection of "match socket"
6. Enchants are showing now / gems are showing as well (it doesnt matter in which sub-window i change the phase it always loads both of it)

**Expected behavior**
It should show the list of enchants and gems of the selected phase on the opening of the tab.

**Sim Links and Screenshots**
![image](https://github.com/wowsims/wotlk/assets/18137824/cfcf4314-152d-4917-83ee-ce072a302a0e)

**Desktop:**
 - Windows
 - Chrome (vers. 118.0.5993.89)
 - Sim-Version 1.5.3

**Comment by jimmyt857** [comment] 2023-12-06 05:11
Likely duplicate of #4026

**Closed by jimmyt857** 2023-12-06 05:11 UTC
