### ISSUE TITLE
T8 warlock 10m doesn't activate

### ISSUE THREAD

**Issue by Talimar** [wowsims/wotlk#2438] opened 2023-01-21 09:36 UTC
**Describe the bug**
The sim doesn't show set bonus or even item highlight as active if wearing 10m tier.
You can see in the screenshot below that only the 25m helm registers as active. 

**Sim Links and Screenshots**
https://i.imgur.com/RdGWXo0.png

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Win10
 - Browser [e.g. chrome, safari] Firefox
 - Version [e.g. 22] 109.0

**Comment by Tharre** [comment] 2023-01-21 22:34
Duplicate of #2431.

**Closed by Tharre** 2023-01-21 22:34 UTC
