### ISSUE TITLE
Import from addon

### ISSUE THREAD

**Issue by gamecam111** [wowsims/wotlk#1622] opened 2022-11-06 21:51 UTC
**Describe the bug**

**To Reproduce**
1. Go to 'Import'
2. Click on 'Addon'
3. Insert data
4. Click import
5. See error lots of IDs just missing

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jimmyt857** [comment] 2022-11-08 01:43
Could you please provide the import string you used?

**Comment by jimmyt857** [comment] 2022-11-10 06:09
Suspect this is a duplicate of #1509

**Closed by jimmyt857** 2022-11-10 06:09 UTC
