### ISSUE TITLE
would be great if you could add Devout Aurastone Hammer. Heirloom item witch spellhance can use with Caress. 2.7 speed

### ISSUE THREAD

**Issue by Azariusso** [wowsims/wotlk#2704] opened 2023-02-23 09:59 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by lime-green** [comment] 2023-04-10 14:44
Duplicate of https://github.com/wowsims/wotlk/issues/1373

**Closed by lime-green** 2023-04-10 14:44 UTC
