### ISSUE TITLE
2x flametongue

### ISSUE THREAD

**Issue by grimmiodji** [wowsims/wotlk#1034] opened 2022-09-12 21:51 UTC
When using Flametongue on two weapons, the dps from Flametongue did not increase by 2 times. (in the realities of the game it increases by 2 times)

**To Reproduce**
1. change "imbueMh": "WindfuryWeapon",  "imbueMh": "FlametongueWeapon",
2. Run dps Test

**Expected behavior**
After dps test, DPS from flametongueWeapon un on 2x

**Sim Links and Screenshots**
Sim with WindFuryWeapon + FlametongueWeapon (https://wowsims.github.io/wotlk/enhancement_shaman/#eJzjYvJgdGIQYpBaxNrEyBaQk1iZWsTBLsAudYyRS0Dg/h4mifP3mJTYth1mOreDiYtT4OsdJiVmEJNX4AxQcu9dZiD3LBMXh8Dl3UwSO24zAXWdBkqcvA3UBVQHUsoncGsXk8QRoAgLkMsA5J8AqvhzkxnK5xS4vAtqqoDAKaDUs9UIzbwC64EGn7oNVcAiMGsPiDy/G0ReBrP7loDt38YkceY2iLVmC4TFItC0m0mJPYClgrGBkVHrBBPDKKAKqGISYJrEaMClxMXBwSjALMGoAIQaLIZgyQNFDpYQZXoODozAlMXBwQRSocHUxahuYGpsYGxgaGqka2BgCoTGxoZA0sDQ2BgobmgIRgamho8YOQT2HGGS2HWE6QUjywdG9lmMDLcYGZRmM3OCTW5Ic5CcNRMETtpDLbtgr5gGBtfsjb4wFcypreIJSCxJzihPLcpWMDJVCJbgGLQpoMWBGqY0nDxCiTkGFloFjsQqBgd6w+zTDo6QaPhp78EIAEzefo0=)

Sim with 2x FlameTongue (https://wowsims.github.io/wotlk/enhancement_shaman/#eJzjYvJgdGIQYpBaxtrEyBaQk1iZWsTBLsAudYyRS0Dg/h4mifP3mJTYth1mOreDiYtT4OsdJiVmEJNX4AxQcu9dZiD3LBMXh8Dl3UwSO24zAXWdBkqcvA3UBVQHUsoncGsXk8QRoAgLkMsA5J8AqvhzkxnK5xS4vAtqqoDAKaDUs9UIzbwC64EGn7oNVcAiMGsPiDy/G0ReBrP7loDt38YkceY2iLVmC4TFItC0m0mJPYClgrGBkVHrBBPDKKAKqGISYJrEaMClxMXBwSjALMGoAIQaLIZgyQNFDpYQZXoODozAlMXBwQRUwaTB1MWobmBqbGBkYGhqpGtgYAqExsaGQNLA0NjY2MDY0NDY0AgkYPiIkYdjzxEmgcNHmCR2HWF6wcjygZF9FiPDLUYGpS5mTrDpDWkOkrNmgsBJe6iFF+wV08Dgmr3RYyaFYAmmQRvpJQ7UMKXh5BEC5nhTxR4QgIRxx2EHR6iAQwIjAMyQc+Y=)

**Desktop (please complete the following information):**
Chrome

**Comment by Wumblesnarf** [comment] 2022-09-12 21:56
flametongue is working as intended, it matches the in-game behaviour. if you disagree, please provide evidence as it has been tested and retested many times. closing this

**Closed by Wumblesnarf** 2022-09-12 21:56 UTC

**Comment by grimmiodji** [comment] 2022-09-13 11:09
Good afternoon, FlameTongueWeapon works great on one hand. But if you change the parameter "imbueMh": "WindfuryWeapon" in the sim to "imbueMh": "FlametongueWeapon", and use MH and OH at the same speed, then the total dps from FlameTongyeWeapon will increase only by the amount of SPD from FlametongueWeapon. When using FlameTongueWeapon on a weapon with the same speed, FlameTongueWeapon only deals damage after it hits MH, but does no damage after it hits OH. (   https://wowsims.github.io/wotlk/enhancement_shaman/#eJzjYvJgdGIQYpBawtrEyBaQk1iZWsTBLsAudYyRS0Dg/h4mifP3mJTYth1mOreDiYtT4OsdJiVmEJNX4AxQcu9dZiD3LBMXh8Dl3UwSO24zAXWdBkqcvA3UBVQHUsoncGsXk8QRoAgLkMsA5J8AqvhzkxnK5xS4vAtqqoDAKaDUs9UIzbwC64EGn7oNVcAiMGsPiDy/G0ReBrP7loDt38YkceY2iLVmC4TFItC0m0mJPYClgrGBkVHrBBPDKKAKqGISYJrEqMelxMXBwSjALMGoAIQaLIZgyQNFDpYQZXoODozAlMXGwaTApMHUxahuYGpsYGRgaGqka2BgCoTGxoZA0sDQ2NjYwNjQ0NjQCCRg+IiRh2PPESaBw0eYJHYdYXrByPKBkX0WI8MtRgalLmZOsNkNaQ6Ss2aCwEl7qHUX7BXTwOCavdFjJoVgCaZBG+UlDtQwpeHkEQLmeFPFHhCAhHHHYQdHqIBDAiMA8mhzxw==   )

BUT!: When using weapons with different speeds, FlameTongueWeapon deals damage after MH and OH hits.
(   https://wowsims.github.io/wotlk/enhancement_shaman/#eJzjYvJgdGIQYpBawtrEyBaQk1iZWsTBLsAudYyRS0Dg/h4mifP3mJTYth1mOreDiYtT4OsdJiVmEJNX4AxQcu9dZiD3LBMXh8Dl3UwSO24zAXWdBkqcvA3UBVQHUsoncGsXk8QRoAgLkMsA5J8AqvhzkxnK5xS4vAtqqoDAKaDUs9UIzbwC64EGn7oNVcAiMGsPiDy/G0ReBrP7loDt38YkceY2iDX1AYTFItC0m0mJPYClgrGBkVHrBBPDKKAKqGISYJrEqMelxMXBwSjALMGoAIQaLIZgyQNFDpYQZXoODozAlMXGwaTApMHUxahuYGpsYGRgaGqka2BgCoTGxoZA0sDQ2NjYwNjQ0NjQCCRg+IiRh2PPESaBw0eYJHYdYXrByPKBkX0WI8MtRgalLmZOsNkNaQ6Ss2aCwEl7qHUX7BXTwOCavdFjJoVgCaZBG+UlDtQwpeHkEQLmeFPFHhCAhHHHYQdHqIBDAiMAOdNz3A==   )

**Comment by Wumblesnarf** [comment] 2022-09-13 16:23
yes, this is correct. flametongue has a very small, nearly-but-not-quite negligible ICD, specific to the rank, implemented in the sim as 1ms. this matches the in-game behaviour and is the reason for having the rank 9 flametongue option implemented in the sim

**Comment by grimmiodji** [comment] 2022-09-13 18:08
Tell me please, How can I get rank 9 FlameTongue on MH and OH? i love this sim) Thx for your <3
mby u can share json for me or link?
 
>Вторник, 13 сентября 2022, 19:24 +03:00 от Wumblesnarf ***@***.***>:
> 
> 
>yes, this is correct. flametongue has a very small, nearly-but-not-quite negligible ICD, specific to the rank, implemented in the sim as 1ms. this matches the in-game behaviour and is the reason for having the rank 9 flametongue option implemented in the sim
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <wowsims/wotlk/issues/1034/1245651251 @ github . com> 
 
 
--
Егор Шелухин

**Comment by Wumblesnarf** [comment] 2022-09-13 18:30
read the tooltips on the imbue selectors, unfortunately its not currently able to be distinguished by the icon but i believe that is being worked on
