### ISSUE TITLE
Crash Report -1398380404

### ISSUE THREAD

**Issue by Lateralusxe** [wowsims/wotlk#4052] opened 2023-11-19 01:19 UTC
Link:
https://wowsims.github.io/wotlk/elemental_shaman/#eJztVmtoHFUU3nPvZDN7bNLJTZpMLpu4DtjE0YTZGddsKjJrtD5RQopY/Fe1orWF0BXUgrKIopuAtjRaGuOjQdP6AJuAYrWhMUYhQkNsa1ELwUbUJTQQKyE1CvXOazdJQyVY/4hnh73nfudxv3vumQdGZZKE22AnwA/kjHQA4CCQIYBxgBxAC5NBhRgxIAkp4dUKG4GF+HTpMxBu3brpyc3b5WKlmJ8GXK28vZOqZ2q08BfDpP8QwYgy2Uk1ekqoq5RnhW2yRqP97uzIb0TdXavRN0eJiNsvbOdEnLB9KcwlyvlOqvYwTRJASEz7hL0rqknCOyTcD75ItYjI2u9eyJSul6mardEiYnbKvYRT7jmqvhJ1c3pcJrI+l4jykUPLWUlSxn50/mfPOqR+6aLqfJ7it2eJmpO9maR0d1CtRAYDWqWNRU/ACwC9ZJbgEAn9L/9ImLHSiB1hGRTSDvdXYIgrMnAUc6pSp0djpAPajIRlGUY8YVpm3LISccs0LSMulAbDSIifYcWNZaRhOdCTSVDl8Z+IMjRC1MMjJPb7MVI/f4wYf0yQHEgzUNwNoWEyKqsUK1HmYZTkPWNUQ5Qx3GA1NiXSefxkJsDNxoRRwOfyeLzRsNLM5jfgVawOFb1UDjOyLuR4IRER5b2gYKmcrYydDwT4BQi7WlSmDmtZdGkKM41yLxQhFQHcG5jJDaxjVwaGvqexWq8SQZFu4pPmghpKgluaex5sPb8Jm1kTRnrB8fn5PYpV2hosH7iQHpbpq30KxSjCr42nuR/DzgGfBTwObByC5ccq8XPgQ4CRASe1cuQTEqhTg3m1py+vOnexr77/Lg3UwwV1eibvMJD3lU98IAXoYDbv+05BfaugiscHVuoVMrDIsLdQljqVQGjGKn1NAZ/5lHh1jhtmjX+4+54nnqZ8KNIUc2+TrJXfjTezFlzlnPxAsHV3Zjph41/RpZWLm0YA3eFDpuEVU3izdTyJGostyPF1hroNUOQGuMSsdAvzLEpwrMa2NLuX34N3stuD8xQNubgJ5oImaGwWLcR0xc/pY8k0lmiXBdGd39CgrdmtfD1ez5pR1StFiLzFp7UgcLlkSxKJkSW45d4TnknZLdqC6+riNo2gKIpoU68ojg+7husYY7VBRucwnBIWFap6nV9CYWLVvApLWLARZddR9zidkdXztRhlPDC98RlZsOW8p4DZ5bwGy/Uyf1M+JzORDh4BrJZH3V1LC3fd5NlPZOj3EOomoe/8t8valLaPRjz9kVSZp1Skqrv3OjJqN3vIuH3FQ66ctM1fSXvPUzsirZsee+DhxzdvfzS2QZX1f/ltVZ9NXYo0mdGRv8mz4WJ2I6m333gpeCwnbqUz7HRqL3jFP2T7a+Xstot+DyQfbHst89KEvRidsW+Z2/NxbvC4XbFr3jwwv99+lWw5at41ZXdMvz7zZ9+UvXy2/66s/HvgvhVH/AV7r3qS

RNG Seed: 1080840554

{SpellID: 58757} failed to cast: casting/channeling {SpellID: 49271} for 61.39666ms, curTime = 0s
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime...

**Comment by jimmyt857** [comment] 2023-12-02 20:56
This is caused by the item swap settings.

Probably won't fix this since it will be re-implemented in APL eventually.

**Comment by jimmyt857** [comment] 2023-12-06 05:24
Re-organizing into #4082

**Closed by jimmyt857** 2023-12-06 05:24 UTC
Labels: wontfix, Shaman (Elemental)
