### ISSUE TITLE
Crash Report -1487623972

### ISSUE THREAD

**Issue by adamthom-amzn** [wowsims/wotlk#2813] opened 2023-03-23 21:35 UTC
uh... I was just messing around with insane blood/frost hybrid specs

Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE1EQ3pnGZHdNmmcUWUOqcYuggcLLLoF62vUHFE9BL/VYpSVQD2kUq4VqKohSkVKwNY2xLcVDj54kamuF/pGDGiEpJSJI2pKI1QZErDn5dlMKgmCK9eaw7zHzzXzf+9l5oswjQYohCEMUYAzgMcBLgDRAEWANMI14lHiRgg5NrOY2wAiAi3MvbLsB1uCF5qstEV4gonsWRCcZyqP0sU62PpnC169QFMhCAeWachJFOxlhuQ91cs04i2yk7wVK/R5GSTB4jVGGUsg+0UF6nqN0c69sYXUcCx+y/D3PeugkXxZRFpg/n0RDyEmGWX6V8adMjAHfF1Ea8GwAFnLnqTF/WjLmlQnTf2MUfi2gNOaWreMVKY4lep+h7OCROoKWJssV47CjyM4RQ+6//dZcdLOMToEHCUMi66IyKOJuHghrrZMQNNovaTZeCcAtCZXys/qOilPSvODjKPRAg6LSAFVoQKWUMp8qDapCGRSgakBRqEr9Bkqp6qd+NQ8S/yCD5H4Gpc/L6I1l8GAsi3Qwi0WwlMAWB140/j4bOeDiyMkrWFk82qrviQ8altIOV3aR1va3mjavKTMYTnR12oPNl86HOloibV4l4D0j8b5/3C2lbn0rZKKp6b/RoY2+8JHNksxLjA7k9XVmUWMv7LT5wIKF4+8n79p06rAfirR906qV7PCUd44OL2vk7fZTFy/PaOnZA/sewdLkr1WlDb3uXUJtbu6HlsvXXn93C/RjE9dW609w+p/WaZxu98y1J6re11aZi/b292W7ztXr1TJ+Atv7uZw=

RNG Seed: 459986057

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 19 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf7360, 0x13e0e90})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:447
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_Frost_FS_HB(0x2042c00, 0x29caa50, 0x2818a00, 0x1b443c0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_frost.go:168 +0x14
github.com/wowsims/wotlk

**Comment by rosenrusinov** [comment] 2023-03-23 21:45
Duplicate of #2664

**Closed by rosenrusinov** 2023-03-23 21:45 UTC
