### ISSUE TITLE
Power Infusion is not cast until after 2 minutes

### ISSUE THREAD

**Issue by Ielsgred** [wowsims/wotlk#1418] opened 2022-10-23 04:17 UTC
**Describe the bug**
Enabling "Power Infusion" causes it to always cast after 2 minutes, even if you also use the built-in timing function.

**To Reproduce**
1. Using mostly default settings (n my case, but I believe they work with all), activate "Power Infusion" under miscellaneous buffs
2. Run the sim (only 1 iteration needed), then look at "Detailed Results" and then "Timeline." PI should show up.
3. Additionally, specifying timing results in more oddities. With PI turned on under Misc. buffs, add PI to the "Cooldowns" tab under "Settings"

**Expected behavior**
For 2, PI will only ever occur *after* 2 minutes have elapsed. I wonder if it starts the fight "on cooldown."
For 3, PI has extremely odd behavior. 
1. When the input is below 120, the timing is ignored (hence "on cooldown" hypothesis).
2. When the input is between 120 and 123, the timing is respected.
3. When the input is above 123, PI is never cast during the fight (even when the duration of the fight is at 180 seconds). 

**Sim Links and Screenshots**
https://wowsims.github.io/wotlk/balance_druid/#eJztUjFoFEEU3ff37piby4VJsBgPi3WbSCAwu8vCpbqNlZUc2KQSgiQIWhxBEAPCGiwkIAQkIQkWdooiWIjomZiQ85CAyhHQxBhOjIVHKhWFkCbO7CliJ6hdXvGZ9/9/7w8zn/cwEqSoiGMYRIViYAa4ga/2PdAS0ADWgRZwtIvBIYUiItOIW0C3VbiaHkemfHbowvAoYwKFZXAhrs2TfNEkN1NfpicPiWfFt01y7Q19zItpXXy/rqmpMDFRJzn1xeYdYmpeK3TStOXE7Qck32oVLN4pdu6TXLtruyldtvSAnQWSjTu2m/lYo2aNdGZXd4zXtYGm7TkvqyRbWpOMTYnJRyZ+2DNxe8HEzzfN/FgLX20aHldNvPSY3ByDQjk9mL4C9E6StY/fMMYZBEkyW+A7PM8gEVpWZcDskN6JPM+xvZ/ABHpCFfhKBZ4XBoEXaOIFgQo19wOvr89XoS4qz9+CZPE7EmuLJN8skrPbpCO1VVLPVqmF1Cdk53CIF3gne37c+eXfzZJLLZ2MNmC525RNaDwSdbVveyA6ODdrsFLqb2capcMjCV6X/CpVrl8c6ygPnTt1+vzw6BnHD50Tkv33X78c/QuXeOXp3/ioYm9l4E+bk8eLp7eiH4pW6Tsxop2H

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox 
 - Version: 105.0.3

**Comment by Gashiraa** [comment] 2022-10-27 13:05
I could not reproduce the issue. Are you still able to reproduce it on your side ?

**Comment by jimmyt857** [comment] 2022-11-10 06:11
Closing because OP hasn't responded.

**Closed by jimmyt857** 2022-11-10 06:11 UTC
Labels: Druid (Balance)
