### ISSUE TITLE
Feature Request: Display Item Soruce

### ISSUE THREAD

**Issue by MikaB07** [wowsims/wotlk#1907] opened 2022-11-23 10:55 UTC
I would like to be able to see what the source of a item is inside the sim, more specifically if its a hard mode item. This provides better browsing experience for those who dont do all hard modes.

I am not sure if WoWhead supplies this data, but if they do would it be possible to display the source of an item on the browse menu.
Ideally being able to apply a filter would be ideal, but most likely hard to intend correctly and without incorrect placement of items (as 80upgrades also struggles with this).

Currently im using 80upgrades on a 2nd monitor to see what items are available to me and then in the sim chose those items. It would be ideal to be able to see this yourself in the sim.

Not much added, but im open to eloborate further in case this request isnt clear.
I have some beginner level coding experience so if supplied with the database i could look into how to format the source info.
Jappa#7419 on discord, send me a message if needed :)

Thanks for the awesome work you guys are doing!

**Comment by jimmyt857** [comment] 2022-12-15 23:18
Duplicate of #1110

**Closed by jimmyt857** 2022-12-15 23:18 UTC
