### ISSUE TITLE
Missing items: Serpent-Coil Braid

### ISSUE THREAD

**Issue by hyperactivated** [wowsims/wotlk#1623] opened 2022-11-06 23:31 UTC
Links to [WOTLK Wowhead](https://wowhead.com/wotlk/items "https://wowhead.com/wotlk/items") for each item:
[Serpent-Coil Braid](https://www.wowhead.com/wotlk/item=30720/serpent-coil-braid "https://www.wowhead.com/wotlk/item=30720/serpent-coil-braid")

**Comment by jimmyt857** [comment] 2022-11-08 01:45
Duplicate of #1399

**Closed by jimmyt857** 2022-11-08 01:45 UTC
Labels: Mage
