### ISSUE TITLE
Crash Report 792542964

### ISSUE THREAD

**Issue by HDBLACKER** [wowsims/wotlk#3113] opened 2023-05-23 13:55 UTC
runtime error: index out of range [25] with length 25
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x191340, 0x22b66a8})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/warlock.(*Warlock).setupDemonicPact(0x318a000)
	/home/runner/work/wotlk/wotlk/sim/warlock/talents.go:559 +0x59
github.com/wowsims/wotlk/sim/warlock.(*Warlock).ApplyTalents(0x318a000)
	/home/runner/work/wotlk/wotlk/sim/warlock/talents.go:30 +0xd
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x318a000, {0x368368, 0x318a000}, 0x21bcc80, 0x3c62b00, 0x21ca540)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:181 +0x29
github.com/wowsims/wotlk/sim/core.(*Raid).applyCharacterEffects(0x1874f00, 0x2a95a00)
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:338 +0x4f
github.com/wowsims/wotlk/sim/core.(*Environment).initialize(0x196b590, 0x2a95a00, 0x21cb5e0)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:122 +0x16
github.com/wowsims/wotlk/sim/core.NewEnvironment(0x2a95a00, 0x21cb5e0)
	/home/runner/work/wotlk/wotlk/sim/core/environment.go:54 +0x4
github.com/wowsims/wotlk/sim/core.NewSim(0x2aba8c0)
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:127 +0x13
github.com/wowsims/wotlk/sim/core.runSim(0x2aba8c0, 0x1bf5a40, 0x0)
	/home/runner...

**Comment by Tharre** [comment] 2023-05-23 19:03
Can you add a link that reproduces the issue?

**Comment by Tharre** [comment] 2023-06-18 14:04
Closing because the stack trace isn't sufficient to reproduce the problem and OP is unresponsive.

**Closed by Tharre** 2023-06-18 14:04 UTC
Labels: Warlock
