### ISSUE TITLE
Crash Report 1956790810

### ISSUE THREAD

**Issue by jsmead39** [wowsims/wotlk#2769] opened 2023-03-12 21:42 UTC
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJzjkudgEmAyYMpgLGBsYGRcwch4gZHxBSPjD0amC0xMDUyMTtICjBKMCowGjA5AJR1QJUwPGJl+MDJaMQgxSK1lbWJkC8hJrEwt4uAU4JKaysjFIfD+GZMSEwMDF4tAw1MmLh6BH3uYJHrklJiv7WDiYhdYe4VJ4p4kUNn0RxBlXAJbbzFJ3BRRYmQAis6EirILNAKNAQrxC3wH6n8nq8R2YgcTEAGNXb4PRK7eCSL7wOzX50EWzb/BhKTq/0MmLpAjjj1kUuLgYDHgDWCOYF7EdJaJawbQglGADQgZkKqjio2DUYJJgbGJiYOLhQOYWKQYuhijDPAAXWMjAwMTY1MQ2whT1sjYwMAYCIHyxkaGpiAVhkC2obGhMVDQ8BGjCMesK0wCc4HJaNoVJoUZV5k0Zl5lesHI8oGRfRYjp2AaGFyz38HIeIuRWxDqTAcFtllMDEqPmTjB3IY0B6iMiIPkrJkgcNLeEiJywV4RZobRZiaFYAlWLRonmA+NDtQwpuHkEaqYQwqAhNne9w6OEP4P+wTGIHAWk299HbhD7qq9MRg8tofIf7Cn1MYdciCD19kX2nJdX1zw1P5NIEjkov3DKpF17g9P2QeBFZyAy+MyBxLrK+1R+S/tYXEPMe8RlP/Mvv/QV42Y/kcUu1/I4OwZEOBwIFYHAARkt8E=

RNG Seed: 3509463093

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf70a0, 0x13def70})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).registerSummonGargoyleCD.func1(0x22f49a0, 0x182b900, 0x23c9b00)
	/home/runner/work/wotlk/wotlk/sim/deathknight/summon_gargoyle.go:38 +0x4
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x23c9b00, 0x22f49a0, 0x182b900)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:471 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x22f49a0, 0x182b900)
	/home/runner/work/wotlk/wotlk/sim

**Comment by rosenrusinov** [comment] 2023-03-13 08:54
Duplicate of #2743

**Closed by rosenrusinov** 2023-03-13 08:54 UTC
