### ISSUE TITLE
Crash Report 1778179360

### ISSUE THREAD

**Issue by zhen246** [wowsims/wotlk#1466] opened 2022-10-26 02:46 UTC
Link:
https://wowsims.github.io/wotlk/raid/#eJztlU9oE0EUxmfeztbNmJQxFFxzirlYCoXZXRbqKal66MFD0Uvx1KitCGpFLEhPsXixIBQlgjlJr5qTELSpDfYPIdUaiWhoY6oUKgUVqiAUT77ZTdHQi4f2ZL+El/ne9zK77PxI+GwrD3Ky9QoT/o3xT2yUho4lLyWvnBuInrg2fPG80SJoZJpyIe5Ngbm4ArGW+Rl4WAIeED8/QExbfgo8JO5juIChppKQWKuCmf6h+akQaUxLNfwqptPYaRXrOFDBDkNL0N/FiWpWa/iQ+I7+9mPcQI0bYgPt6LxaFXG1ntU4E+U8YB1/pmphUtWNvJp4mQezWFM+5XVv5iHGDSppL+vTb9COcSB7atIIsQ/ykEFN6hJytbuL9tAwiTAOhj5Gj7jSsaV0LMt1HMtBYzmOdNHbjtXZaUsXQ2nZq9Q0Uh9BVAtgLhUg+msF2mcrIIsVWKdsg+7LULJM/+ZtIsAXkLfg8aHLZ5PXo6eGLgwPGLpoieQVbk/woMsKt9wsvF5UuG0q3AoebjkMiysNa4i3eOTLCEVI1BqkeUGreJcDc05hVlBY7Rf1BmZ4HwFxZ7IxJ8QXxPHzI7wYWn/LdG6LszGPsMyUql+fq1pfUhMFvOirmlpN5PwVEy+QNcMAqfeyfrZH2jaNkDNhfGDMBKl1gYJMgEnHaLtEopAy6dpOp7RdpMrywHKlJW0EDRNkzLVWadCYWQNRXEPKys1k7cH0f2lXYdr6kWr+i2xyYdJBIn28jYfpNqkuYwzwjcKiqw/VxRtn6u4ZIzpjukZIo/tH3knH6hDwXGowccDvtyUOZR4oleJH/c6b+OFBT+/jdhaip01j1zm5ldiJXVKluR3Z51/kP6uT9US37zfjPbSf/gbihCs1

RNG Seed: 0

Aura Garrote already registered!
Stack Trace:
goroutine 7 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xbcc60, 0x7a85d20})
	/opt/hostedtoolcache/go/1.18.7/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*auraTracker).registerAura(0x7aa2488, 0x7aa2000, {{0x1ea378, 0x7}, {0x1eba9f, 0xa}, {0xbe24, 0x0, 0x0, 0x0}, ...})
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:311 +0x3d
github.com/wowsims/wotlk/sim/core.(*Unit).RegisterAura(...)
	/home/runner/work/wotlk/wotlk/sim/core/aura.go:341

**Comment by jimmyt857** [comment] 2022-10-26 02:49
This looks like a duplicate of the previous report.

**Closed by jimmyt857** 2022-10-26 02:49 UTC
