### ISSUE TITLE
Crash Report -208347869

### ISSUE THREAD

**Issue by RalfK92** [wowsims/wotlk#2770] opened 2023-03-12 22:39 UTC
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJzjkudgEmAyYMpgLGBsYGRcwch4gZHxBSPjD0amC0xMDUyMTtICjBKMCowGjA5AJR1QJUwPGJl+MDJaMQgxSG1kbWJkC8hJrEwt4mAV4JJay8jFL7DiBZPEK1kltiWHmU7sYOJiEXj0mImLR+DxJiaJHjkl5mtAMXaBSfuYJO5JAlUvA6p+KKnEBlQKUs0jMA8o0wVUB+JxCnQ9Y4IxG2FMdoHevUwS72SBun88ZpJYANQ9cyfUrh0PQGTfPhD5ZBGIfL0XpOPSbiaJ1XJQRpcMUPzGAyYlDg4WA94A5gjmRUxnmbhmMDGMAqxAyIBUHVVsHIwSTAqMTUwcXCwcwEQkxdDFGGWAB+gaGxkYmAIhEBhhyhoZg0SNjYHyxkaGpoZAMUMg29DY0NgYyH3EyPCCkeUDI/ssRk7BNDC4Zr+DkfEWI7cg1EkOCmyzmBiUHjNxgrkNaQ5QGREHyVkzQeCkvSVE5IK9IswMo81MCsESrFo0ThwfGh2oYUzDySNUMYcUAAmzve8dHCH8H/YJjEHg7CTf+jpwh9xVe2MweGwPkf9gT6mNO+RABq+zL7Tlur644Kn9m0CQyEX7h1Ui69wfnrIPAis4AZfHZQ4k1lfao/Jf2sPiHmLeIyj/mX3/oa8aMf2PKHa/kMHZMyDA4UCsDgBq6bz4

RNG Seed: 3119857062

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 17 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf70a0, 0x13def70})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).registerSummonGargoyleCD.func1(0x289cd10, 0x2182500, 0x19c78c0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/summon_gargoyle.go:38 +0x4
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x19c78c0, 0x289cd10, 0x2182500)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:471 +0x13
github.com/wowsims/wotlk/sim/core.(*Spell).makeCastFuncWait.func1(0x289cd10, 0x2182500)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by rosenrusinov** [comment] 2023-03-13 08:54
Duplicate of #2743

**Closed by rosenrusinov** 2023-03-13 08:54 UTC
