### ISSUE TITLE
Offhand list completely empty for warlock sim

### ISSUE THREAD

**Issue by DeanGrasser** [wowsims/wotlk#3980] opened 2023-10-29 21:42 UTC
**Describe the bug**
Intermittenly the offhand screen displays zero items no matter what filter I try to apply

**To Reproduce**
1. click on the offhand item

**Expected behavior**
A list of offhands should appear, the list is empty

**Sim Links and Screenshots**
link
https://wowsims.github.io/wotlk/warlock/#eJztU0FoE0EU3f93m+6OSqZLD2tIS1xEg1CYJCzUg8zqxRyjvRTxoAeLiIfiSeMlFkPTerCCigYFqZeexJxUiliiRXpQigGlVkrS2FqxalAjRag4s5teRNBqvYjvMDv//ff/PGb/kM06UmTYCUnohl7MAAwBlPGTehNwDGASYAFgV4sOEWTgQkqqYATAVELDgT4IpI4ePHHomN5M9dArIEGaG1KtxTY7MF7E8TtIDPqojLY6LbbraVbkZttWonsf0RoUUUFEJp3/gNaSbhuiSKQlt4EuC+6KaWsiUgillZdonQ/bzQUvr4iiUSE4F/aKfFJw1axqXWu3jYLXSHoI0hmhuxgWpnyRQWcGVN+GQW9V0feg0cdVuZZyqnD34oJqfWl41ehyvyqk7ypCOjqPdlAHBp2Q0rqbjkMOYBjrSMZQ+Y8/gslWW5GmOlC08DAZAXIJxGgeCRHJaZYY2Kj8S5iEUMBnBmFrPOEwxuIsIZaEE2NxRxKJRCzmxDo6HJlkzInNgqVf7Vfp1BxapTmM9JUw+vUJslMlXIB1NdDyYBLqD4upN8y4RVSeg5JHZaoxCltc+4xqeNtMj9vik63uxvxliQm+3Wcm+aYeD095fBojXVbTtr88TNEBdy3aZCYe/KRP15qc8zvw7/bue3enHy/xA7D3h8/0ZOuN3ZX0aU6eXe/dQR7yZCUtGe5na3xFd78e3X+2+JZ/lp96mS/uud2effOaf9/vX8fqn+m+RkXtl+/qG3KGtEw=
wowsims.github
![image](https://github.com/wowsims/wotlk/assets/33469123/4a8af805-a056-4fde-be8d-2e29628936cd)
local
![image](https://github.com/wowsims/wotlk/assets/33469123/0b28c849-ae8f-432b-9a2e-a3a8c4e595b5)
Filters
![image](https://github.com/wowsims/wotlk/assets/33469123/8ecb96bd-20d7-406e-856c-8f09242dcb4f)
Changing to mage, the offhand list appears just fine
![image](https://github.com/wowsims/wotlk/assets/33469123/4b27928c-5d37-4b8c-9492-038bd372d793)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Ive tried for both the wowsims and local sim, issue still occurs
 - 
**Additional context**
This has happened a few times before and after days or weeks will resolve itsself

**Comment by DeanGrasser** [comment] 2023-10-29 21:46
Im going to leave this open, but I just created a sim link and when I clicked on it, the offhand is now populating.
![image](https://github.com/wowsims/wotlk/assets/33469123/ef26c46d-e257-4a6b-83a6-1ea75d96d2ad)
However, my previously cached sim is still failing. So while I have a workaround, the issue is still there

**Comment by lologarithm** [comment] 2023-10-29 21:57
You probably have a filter on the mainhand slot for 2H weapons, which applies to the offhand slot and there are no valid 2H weapons on offhand.

**Comment by DeanGrasser** [comment] 2023-10-29 22:00
The mage sim, which has been working, has both selected and the offhands are populated
![image](https://github.com/wowsims/wotlk/assets/33469123/5b3bc058-2037-4a3f-890f-5e3be08a3fe2)
![image](https://github.com/wowsims/wotlk/assets/33469123/1695845c-523f-4554-a4b5-0e61011d77c2)

**Comment by lologarithm** [comment] 2023-10-29 22:38
Do you have the 1h box checked on the main hand in the warlock sim?

**Comment by DeanGrasser** [comment] 2023-10-29 22:39
Yes
![image](https://github.com/wowsims/wotlk/assets/33469123/9b2f224a-24d4-4519-8b4a-e128b7e0f67a)

**Comment by jimmyt857** [comment] 2023-12-06 05:06
Duplicate of #4026

**Closed by jimmyt857** 2023-12-06 05:06 UTC
Labels: UI/UX
