### ISSUE TITLE
Crash Report 1975819248

### ISSUE THREAD

**Issue by Xssesive** [wowsims/wotlk#3201] opened 2023-06-22 21:03 UTC
Link:
https://wowsims.github.io/wotlk/rogue/#eJzjUuZgEmAyYLJg9GCMYCxgamBknMDIuIKRcQMj0wFGxguMjC8YGZ1EORgVmDQYDRgtGB0YA0AKQUqEGKS62JoY2QJyEitTizjYBdik3jBy8Qs8+8Ek8VJWiW3bYaZr/5m4OAWuvGdSYt60k4mLR+AJUO6BLIy38zOTxFQZCI9f4AVQ7gdQH5AHEhAQ2PyBSaJVTokdIsDAxSvwHKhkiowSC5grJNABVNAvo8R5F6wApElI4P87Jon3skqcm+Bi/AJP3zNJTJNRYoOoA7roMcxFnAL7vgGZQAkuFoHZH0Dkyicgp20BGn1WFiLDIzDzPYLHKbDwM0SLEj8HOEwCWCNYKxg7GBkXMX1l4jrAxDAKKAJCBqTqqOLgYBRgkmAqYIyS5GLTACZoD1YpfgFGCSaD/zDA2MWoqmtkYAxExgaGBsamBoZGpkCWsamREZAw1DU1NQAB00eMEhw3nzIJzG1nlrh9mkmh6TKTxr9LTAaNl5leMLJ8YOSexchwiImhExrPlg63GBlmMTEodTNzggUa0hwEIVJ2DpKzZoLASXtLiMgFe8U0MLhmb3SbSSFYgkmL1umlxIEapjScPELAHG+q2EMOgIRtx2EHR6iAQwJjEBk58YM9dd019AHpOTGKZB0A8DefXQ==

RNG Seed: 2144856508

runtime error: index out of range [5] with length 4
Stack Trace:
goroutine 10 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0x193660, 0x1868d50})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/rogue.(*Rogue).ApplyTalents(0x1bbe000)
	/home/runner/work/wotlk/wotlk/sim/rogue/talents.go:22 +0x9e
github.com/wowsims/wotlk/sim/core.(*Character).applyAllEffects(0x1bbe000, {0x36b4c0, 0x1bbe000}, 0x1b8e460, 0x1b6d680, 0x1af3ab0)
	/home/runner/work/wotlk/wotlk/sim/core/character.go:251 +0x16
github.com/wowsims/wotlk/sim/core.(*Raid).applyCharacterEffects(0x1875680, 0x1b9c480)
	/home/runner/work/wotlk/wotlk/sim/core/raid.go:338 +0x4f
github.com/wowsims/wotlk/sim...

**Comment by lime-green** [comment] 2023-07-01 21:17
Duplicate of https://github.com/wowsims/wotlk/issues/3218

**Closed by lime-green** 2023-07-01 21:17 UTC
