### ISSUE TITLE
Bear form armor contribution

### ISSUE THREAD

**Issue by biogopher** [wowsims/wotlk#1954] opened 2022-11-27 02:20 UTC
**Describe the bug**
Bear form only gains bonus armor from cloth and leather Items.  This means that rings, trinkets, weapons, neck pieces do not get multiplied by the bear form buff, neither do enchants like the engineer enchant to gloves.

**To Reproduce**
1. Go to 'Gear'
2. Click on ''Trinkets
3. Scroll down to 'Defender's code'
4. See error " Armor is increased by ~5000 instead of 850"

**Expected behavior**
Should only multiply armor of gear labeled "Leather" or "cloth"

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] PC
 - Browser [e.g. chrome, safari] Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by psiven** [comment] 2022-11-27 04:05
Thanks for the report, please note the bear sim is unreleased and looking for a druid maintainer. This fix will be in the queue though.

Closing as a duplicate of #1527

**Closed by psiven** 2022-11-27 04:05 UTC
Labels: Druid (Feral Tank)
