### ISSUE TITLE
Feature Request: Tracking item changes between simulations

### ISSUE THREAD

**Issue by krabpeople** [wowsims/wotlk#1440] opened 2022-10-24 21:58 UTC
**Is your feature request related to a problem? Please describe.**

I do not have a good way to track and manage which gear/gems/enchant changes between simulation result and how they affect the simulation result.

**Describe the solution you'd like**

I would like to see which gems/enchants/gear are changed between each simulation. I would like to see historical simulations results as well as the gear that was provided, and then compare the gear vs either currently equipped gear or a set. A solution would be to have a section with DPS sim results that can be expanded upon to provide the gear that was ran for that sim.

**Describe alternatives you've considered**

I have tried using excel/word/notepad to track each simulation changes and their results, but it is painful and hard to track.

**Additional context**

**Comment by jimmyt857** [comment] 2023-12-09 23:06
Duplicate of #1248

**Closed by jimmyt857** 2023-12-09 23:06 UTC
Labels: UI/UX
