### ISSUE TITLE
WotLK Warlock Simulator Issues in Google Chrome

### ISSUE THREAD

**Issue by Lublub782** [wowsims/wotlk#1292] opened 2022-10-13 21:57 UTC
**Describe the bug**
The WotLK Warlock simulator does not fully work in Google Chrome.

**To Reproduce**
1. Open simulator using Google Chrome.
2. Click on on any of the item slots and an empty window will appear (see attached screenshot). This window should be the item selection window, but it shows nothing.
3. Buttons are also missing in the top right corner of the simulator. The missing buttons are the Bug Report. Import, Export, and Options. These buttons are viewable when opening the simulator using Microsoft Edge instead of Google Chrome.

**Expected behavior**
The item selection window does not show when opening the simulator using Google Chrome

**Sim Links and Screenshots**
See attached screenshot for example.
![Screenshot](https://user-images.githubusercontent.com/115745537/195718189-da8560a7-31b8-4e9c-b94e-0ba6043bdf0d.png)

**Desktop (please complete the following information):**
 - OS: Microsoft Windows 11 Home, Version 10.0.22621, Build 22621 (64-bit)
 - Google Chrome, Version 106.0.5249.119 (Official Build) (64-bit)

**Additional context**
The simulator does seem to fully work when opened with Microsoft Edge.

**Comment by jimmyt857** [comment] 2022-11-10 06:14
Suspect duplicate of #1509

**Closed by jimmyt857** 2022-11-10 06:14 UTC
Labels: UI/UX
