### ISSUE TITLE
Full Raid Sim shows incorrect results for individual players (offset to the next player) 

### ISSUE THREAD

**Issue by spyral98** [wowsims/wotlk#3494] opened 2023-08-18 20:33 UTC
**Describe the bug**
When doing a full raid sim and checking the results of individual players at the Results tab, the results from each player are offset to the next one (results of player #1 show as the results of player #2 etc...). Checking the results of player #1 shows nothing. This happens to both the web hosted version and the local hosted one.

**To Reproduce**
1. Go to 'Full Raid Sim'
2. When the simulation is done click on 'Results' tab.
3. Click on the  'All Players' droplist.
4. Click on any player.
5. The results for that player are not correct (shows the results of the previous player).

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - Browser: Firefox
 - Sim Version: v0.1.42

**Comment by kayla-glick** [comment] 2023-08-21 05:01
Started looking into this today and just leaving some notes. The player filter starts at 0 and emits `filters.player == 0` when selecting the first player. But when the execution gets [here](https://github.com/wowsims/wotlk/blob/f8b540c0c95ad745851d7f8e2fbf800a958e9712/ui/core/proto_utils/sim_result.ts#L106C1-L108) it looks like the enemy unit is actually target 0 and the first player is target 1, so the numbers are off by 1. I'm not sure whether or not the issue is the enemy unit coming first or the unit picker values being off by 1
cc @jimmyt857

**Comment by jimmyt857** [comment] 2023-08-21 16:09
This is an issue of `unitIndex` vs `index` in the backend. We should try to use `unitIndex` everywhere and only convert back to `index` for determining the raid position in the UI, but I guess we didn't catch all the cases.

**Comment by jimmyt857** [comment] 2023-12-06 05:22
AFAICT this is fixed now.

**Closed by jimmyt857** 2023-12-06 05:22 UTC
Labels: bug, Raid Sim
