### ISSUE TITLE
Crash Report 415188709

### ISSUE THREAD

**Issue by hpois** [wowsims/wotlk#2812] opened 2023-03-23 21:33 UTC
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE0EU3vfcJruLoWOQssakxNWD1BYmu+TgabeeiiAGvVRvPVhzCLVVD1oR0vqD6CEg/iRR1LYUil6KB41FsRCLBrRNIRVR0GgqiS3q2lAIPTmbzUUQTLHefMws773v/c3sN5IiIEGKYeiFKMAYwDjAJEAWoARQAcwi7iJ+pGBAJ4u5AHAHwM158g2D4AhFuk4eOio4ieSZBamRjJRQ/uJTHA/SOP0KJZG8KaKy7nEKpfVklGF5n201kmwR5atexcEs23GbwRWWeiuDbEku8mEe5XPNCs9gjplDDL/iVXgGciz80UdUxHQK7SW5yXQe5e8+RbQLWjWdJPYE5WteNsb7Qm0MkYzN11SeTE5Y38UZq1uZzXPXU+vGMXdsAhWXgNQV4jv5E9a5h5EdKY7cf/mtuOlqM/pFAWQMS4xQK0ClJgEIY1kHhCwmpqocNAE8TaIdfsDYYCum7ocW7iK0qhoNUpUGNUop0zW1TVMpcwWpFlRVqtGAakFUC9DAJ5CFGzkk13Mof/2M/ngOt8fnkCbmsAS8Cc4kCBKyX8/2W+CSyCkLaHeOdhubkglLMvpOe4SsvqW7Kq91NY29xSj2O9sjh7siR3r8+2W+5R/TxBww1qJMNPPsb+qMzyydaV9tUvUCoy+XjFqmqXdYj2tf9W21Li4MvJtyGKf3xvD4t2W93qKR3c0/RrGgN2SHZnM9U3phRzhx79Tg01+jTH348rFt90fAqJyfaHPAip4Q94SjG019+RIGD25G4099Qi/6vM/7btY911qJm5bLDwmc3WrUm/ETuxXC9A==

RNG Seed: 2825999821

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf7360, 0x13e0e90})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:447
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_Frost_FS_HB(0x2173700, 0x23548f0, 0x2360a00, 0x19c8ed0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_frost.go:168 +0x14
github.com/wowsims

**Comment by rosenrusinov** [comment] 2023-03-23 21:45
Duplicate of #2664

**Closed by rosenrusinov** 2023-03-23 21:45 UTC
