### ISSUE TITLE
Missing Heirloom 2.8 offhand mace

### ISSUE THREAD

**Issue by Drustic** [wowsims/wotlk#1652] opened 2022-11-09 03:44 UTC
https://www.wowhead.com/wotlk/item=48716/venerable-mass-of-mcgowan?bonus=80

This is a Heirloom wep, but might end up being BIS for FOK spamming rogues. Need to set it as lvl 80 with correct stats

**Comment by jimmyt857** [comment] 2022-11-20 06:49
Duplicate of #1373

**Closed by jimmyt857** 2022-11-20 06:49 UTC
