### ISSUE TITLE
Crash Report -1616281908

### ISSUE THREAD

**Issue by cloudsMountians** [wowsims/wotlk#2092] opened 2022-12-08 15:04 UTC
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztUj1oFEEU3u/d3t3caLxRLCZHVs5FQQIHs7seaLVrqhQWBzYpY2GwsFArY3UEhaBIFCS5XLCxCqKgROGMUQKxSeUVlxRCQATlggbTGYRwvt0zgXQWsfNjvt033/vemx9GnhSkyNBlXEUVmAWeA4tAE2gDW6AmUY0woIpkEGGIbeOJ7YhVeJoeQ6Zy5eLopesCShZeQebV1w7pdcfNNJZovUHSVttzJA+qjQXSnxw3tcpaVj14R/qnE7tZftnrZhYaxENK9Ygzt4+5sGSPmnlD+mGfa3PGkjn1Yo7cVOzKq+9c9sPZLcuqibekJ/s4uMf1HYeDu6+TwFbfPsS7WJyPbW3e3JMCB9ucnS2wPjFPbl6Q6TmDij1k34hP13+frP/Yg5u2gKZfGJYDNeAxTkgSOSaYxEwxM8w0M8u0mYcEBlHBtW6HzXA0+Y8vRfx09OEdtYj+A6KzA9xByXilwDfGD8omOO37JjCeHxhjgsAzXlD2SjzjfGDK/PkMLWZapKZapDe+ULHWolO1FTLTK9RGehO5OqyPsOpkuWuUS9asjkR/Vj8a9danYyyHZ7tKMzw+kmA19J9R8YIW//wx3Ir2o0t1+f2+9PkbdO/q/Fp0rjvfCgcxjN+mxYp0

RNG Seed: 1253413572

you can't unh sub without ERW in the opener...yet
Stack Trace:
goroutine 15 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xbc4a0, 0x2c88a0})
	/opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).SetupRotations(0x1736b40)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:163 +0x96
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).Reset(0x1736b40, 0x1e229a0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:300 +0x20
github.com/wowsims/wotlk/sim/core.(*Character).reset(0x1cdd500, 0x1e229a0, {0x2cda00, 0x1736b40})
	/home/runner/work/wotlk/wotlk/sim/core/character.go:359 +0xf

**Comment by enhancedgore** [comment] 2022-12-09 02:01
the error message says "you can't unh sub without ERW in the opener...yet"
because there's no code for non ERW opener for frost sub unholy yet.

**Comment by jimmyt857** [comment] 2022-12-10 05:03
Duplicate of #1950

**Closed by jimmyt857** 2022-12-10 05:03 UTC
Labels: Death Knight
