### ISSUE TITLE
Crash Report 509248987

### ISSUE THREAD

**Issue by Zamchalz** [wowsims/wotlk#2214] opened 2022-12-20 08:35 UTC
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztU01oE0EU3vfctpu1pWPIYQxNWfdUCoHZXQN6kFm92IOHWC89eLAHiwcPxZPWS5QWpIK9iKYpeLA9VAQRiyXWCGK9BFoNmjQgCP7QklCKQRCDtNWZ2XrSYoV482N5vG/e9352941pG0iQ4RkYhBTANMB9gKcABYAKQB2wgHiEWMjAhz6huaI0YS16p+kyNCfP9l84fc5oImb0AZjtZKWMtBqzm2fn8cUimjrZmEGzlazlkL6L2btyWTRbyOvHSL/GpFoc14X6Vh5lpI2MishIp60Lpgk6Iej1ji3aSpbmUGnFI6qszCH9FBPHmVmkNzqC4jqpzkh79ZG016akXX0p5a9EremocO7mlKOT9QW02w1kbQcgqffp5+Wr3cYnaKZR+4/fImz9STGkG0DxG7hmROwV9EAS+lXAH/NTam/onkBZ4xZ07za+/wSMQpw5cc9lzPUSzNvvusxjjusxxjzPYY6XcOKCibjHEsJ8AGpMFJHcLCJdW0YrXcSudAnZeAkr0FKDUAa0N6BlULOXMaR6pgb8re4Rf29mXCLPDwYnBb5vQGGJuw/ROkGN7n+8CLVLfiPKpPLPG1LnbxB8s2Nv/cMBr/MeOAW96vLMf+k6OfYs5JcnBw+Z5Y98pzWD/1HlQX5pm7waz3aOrB7PbvJe5VR4kLfBp2S7yQqP3Dv6fijyedu+F5VgeMdzNQpha3FBwvCDSdd/meAHUHS9dA==

RNG Seed: 3966514923

you can't unh sub without ERW in the opener...yet
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x10
panic({0xbefe0, 0x2df848})
	/opt/hostedtoolcache/go/1.18.9/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).SetupRotations(0x14952c0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:163 +0x96
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).Reset(0x14952c0, 0x15144d0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/dps_deathknight.go:300 +0x20
github.com/wowsims/wotlk/sim/core.(*Character).reset(0x1c06a80, 0x15144d0, {0x2e4e88, 0x14952c0})

**Comment by enhancedgore** [comment] 2022-12-20 15:16
the error message says "you can't unh sub without ERW in the opener...yet"
because there's no code for non ERW opener for frost sub unholy yet.

**Comment by jimmyt857** [comment] 2022-12-23 18:46
Duplicate of #1950

**Closed by jimmyt857** 2022-12-23 18:46 UTC
Labels: duplicate, Death Knight
