### ISSUE TITLE
Crash Report 1897335893

### ISSUE THREAD

**Issue by CharWS** [wowsims/wotlk#3370] opened 2023-07-24 15:46 UTC
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztVV1oFFcUnnPuuM7cJt3pdbtML0a2wyJhYWV2tymtUGYVxL7VnxcppdiHSCkiqXmp9iVR05qforalxBVFEykSxYjgX38kjfoQ6MJWEwO1D7X2ZyW0WZTg2v+zc2e3Viqbttqnnp1z59zvO+fcc8+97HDHQAtdfBnaoAPgEMAxgBGAAkARoAxYQFxqxdCFLKwhn+2+j9Dk1oe2QGjF+pc2tW40TIvLK8DDVmkns683OaELozh8BrlpnRhiDrtIZoN1g7gvmxw27M9mepl9q0lxYesH4soUR9zl35A3WteI7lrg6ERrNJ0m/t35wTRsfdTLHJPsYf/hwhoh9+mmKvaJn/P4ELPfm+/nVLV8kQtqMa2uvsDUrbNDjMYPuxmlmdzK7EPSMfeNoXq4RtyeHuY0Gug2PgUr9NcqHRjAGeQjqP0v/0qE+3cjNusG2PgjrOHL+ukYIM7RMEmBFEkZaYh0DulcUp30YYOu7rPwqspQ8jb57+3nsgVAGX6kCscgobnQA8lkJu26LfQjSSfTGZemmXRLZfDBTIrGVCaVISP1FdjG3nG0vv8G7dw4xvrHsbl/At3dE1gEvQRzc6CN4mf6fgBucUOGuG5030ahJ9Nuew3J5StIipBwgHT2McGST9YA650PkIBUu9AlLtbE2yB3gOgDHnqurXVD60ahwn7KM8GlwUNG5xssBoHdc4f93fDduIos3MTAOvBm1TrZwepEfXuYBdaZPAhbRnmDw7mRriCnjrJaTVLadzDvE/NHjWnp8oUizu1E1NCF8Uo1ljy4nlrU0n5XvtxbTMSlw20R5eYABIVyM1c1a7uo71Wpv66X33vae60nrlzE48Lh0UTkTxXTm+MTf1Xvo3IeN4/7SY/kFXxpFxMNUrX06q6gvT5TnsIao5pdnX3tHwPdAKl9DloONaeXmeoCv5gNbnIk+1hud0XGvKcVUvAeX+fLZS99BWOr7TmJB/zf1dydvR9pOsbO18mz+r6s809E9fbj6ewSNS97a2GV/1U4N9P8wo5RMzs52PYMn7zmzTajOrXrnoqfuEdcyTu9oGtq5elfvVW+UfRU3C/ewcpyg0UvcnT51c2RG/dc93XfYdus6/qvRbj5TytiZNWOfq5b6fPBd6Q06z39DtjNKd4=

RNG Seed: 1958109373

protoID is nil
Stack Trace:
goroutine 6 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
main.computeStats.func1()
	/home/runner/work/wotlk/wotlk/sim/wasm/main.go:49 +0x10
panic({0xe2c20, 0x37f130})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.ProtoToActionID(0x0)
	/home/runner/work/wotlk/wotlk/sim/core/agent.go:126 +0x1e
github.com/wowsims/wotlk...

**Comment by rosenrusinov** [comment] 2023-08-21 09:12
@CharWS can we close this if you can't reproduce anymore?

**Comment by rosenrusinov** [comment] 2023-08-22 07:58
Taking

**Closed by rosenrusinov** 2023-08-22 07:58 UTC
