### ISSUE TITLE
Missing items: [Drape of Icy Intent]

### ISSUE THREAD

**Issue by jakess009** [wowsims/wotlk#2063] opened 2022-12-06 05:18 UTC
https://www.wowhead.com/wotlk/item=45461/drape-of-icy-intent

Hard Mode Hodir

https://wowwiki-archive.fandom.com/wiki/Drape_of_Icy_Intent

**Comment by lime-green** [comment] 2022-12-06 22:28
Dupe of https://github.com/wowsims/wotlk/issues/2034

**Closed** 2022-12-07 07:45 UTC
