### ISSUE TITLE
Elemental Shaman - Stat Weight Calculation broken

### ISSUE THREAD

**Issue by KryptixGG** [wowsims/wotlk#3872] opened 2023-10-12 19:57 UTC
**Describe the bug**
I've played around to fight the Phase 5 BiS Set and for some reason the spell hit stat weight is 0 even when I am unter 17% hit und the haste weight is very high - it seems too high since it at 1.29 even though I already have >1400 haste and it should be getting lower rather than higher with more spells hitting 1.0 sec casttime. From that time on the stat weights are always the same no matter what gear I try: 0.22 int, 1 sp, 0.08 MP5, 0.00 spellhit, 0.67 spellcrit, 1.29 spellhaste

**To Reproduce**
I dont know how exactly to reproduce it sadly.

**Expected behavior**
Stat weights should be correct and adaptive to the selected gear.
**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.](http://localhost:3333/wotlk/elemental_shaman/#eJzjEuNgsmD0YHzANIF5AyPTAUbGC4yMLxgZnXg4GCUYFZgMGB0YIxiFgGqkmtmaGNkCchIrU4s4mATYpR4ycvELLJ3ALPFGVont6CGmjTuZuDgFlvQwKzGDmDwCi4Fyj2RhvO2rmCUmy0F4/ALLgXI/gPqAvGNAAV6BbUDpOUJKLEABBiB3GVB+iowSy4KTQC6/wO5VzEqct3cyAblAxCUk0NbDLNEpq8QJ0X8TbGY3UGyaDNhMiFtedEPdwilwrxPIBCljEdizihlIrulkBjpqHVDLL7gTd3QzS7zgUGK+DVY3q4tZiZeD0YAxgCWCpYKxg5FxEdNXJq4DTAyjgCIgZECqjip2DkYBpgZGxiQdLgkORk+wYEOAQyCE4eDgwJjBKCXAwSjFBVTILMGsAIw2BaYuRmUDU2NjAwNDUyNjI0NjY1NDYyMjYwNDIEPXwMAUCA2MDR8xSnDsPsIkcOEpk8SBI0wKv+8xafy6xGRw9irTC0aWD4zssxgZDjEx3GJkmMXEoPSYiRNs6YEiB0GI40QcJGfNBIGT9pYQkQv2imlgcM3eaDOTQrAEq9YM2qaaD40O1DCm4eQRqphDCoCE2d73Do4Q/g/7BMYgvPlMM6b/0FeNM/aooh/sq0XWuT+s2gIXL7Tlur644Kn9kgIQ44s9ujnDHZCez6JI1gEApEWbaA==)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser: Microsoft Edge
 - Version v0.1.51

**Comment by ghronkrepps** [comment] 2023-10-20 04:04
I'm noticing similar issues. The total hit value is 19.20% and it's still valuing hit above others. Also, the stat weight calculations are just off. Here's the setup I am using:

https://wowsims.github.io/wotlk/elemental_shaman/#eJztU01oE0EU3vd2TSeDbcalyBoS2a4eYkGYZAnEg+zqRY/RXop4qdIi2EMsQjWiBPFgqqCoCA09+IcUBI3QS28xpkJASxBsQVFsNZKDYgoWbXuos9k0oEglWC/itzC8933vffOYnaEBgjHYC5cB3mJWGQXIAuYASgAVgN0qAQ105BADW1TFoRtUyf/AcxY88f6ek70DBFmLfxqojz1eQO1j0PBM5PHVOFIvW7goG7ITrmePhDYbNOSHtezrZ9SubnY1H5sQ2jfRd6OITwTRypYvyNqIaihClkRaEPq1QD31sex7NLyiVlg5biqbqqKWDtY40e96LokdrgcMT71IYa/TsljLV5x1suowk++cUc6JwsXGYJ9EViHuYArLDMlGKwEOcaV73Qk4D3AL55HmUPqPP4LKm+1IegkwHAWagEMd1EcwBPtcZavNwd9GwE9FhayhLv7XEGzhUdPkPByNmJGwaUbDZiRi8rAItnMeFR83w7OgkbECslIZtVwB9aU3GFp8jvzZC6yAUoWWDFjUT9tIeqO+vAJQSX0kmzKqkA/35AYjbieVyd0zK0TIzqP0EqQMSsZN2VvjUn32Bldttzdlhh0UrR0uU7I6+mqYsiJzmBg5nfTGe44fPjLYO3BU79JI51++eaG0vRY2qWLhNz5dq+k81pnYtRZz/Aq1k06pM/YwuIc/btX3qlj7V33b2w5eys+Hnlo/slXrVPv9PTPJsQZ/bCedvp0oW3cSTvDF+tnnX0fzb/tA0x3fAZaHuOE=

![image](https://github.com/wowsims/wotlk/assets/5125907/73804c8f-9d29-4da5-9453-bb498204cde3)
![image](https://github.com/wowsims/wotlk/assets/5125907/abb1c986-7110-4221-9c52-a3f3c3943c55)

**Comment by jimmyt857** [comment] 2023-12-09 22:15
There was a bug with auto rotation not being properly propagated to the sim when using the Stat Calc action. It's been fixed now and I suspect it was the root cause here, so going to close this. Feel free to reopen if you still experience any issues.

**Closed by jimmyt857** 2023-12-09 22:15 UTC
Labels: Shaman (Elemental)
