### ISSUE TITLE
Crash Report -761394477

### ISSUE THREAD

**Issue by Koziyak** [wowsims/wotlk#3080] opened 2023-05-12 04:22 UTC
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVD9oE1EYv+9Lerk8rD5DhmdIarzFIArvcgTaQe50UbdUlyIOOlgUHFoH0S7GYlAU/EcVzOBgB506yoENapOlSFWCWFAQ01Lb2kpToTapCn53pw51kGI7CH7c792978/v9/juu2MRDSS0wl7ogNOQA7gGsBuzEMFWiN1Re0HNnjhy5uhJDXko5gDbwM9Po3iZ0NUHJSw5yIL8/jiydfzLFIp3CT2wSL4QvziB4macsr+Ru07Zz0bQjTB+ZRxFvkUHhTXzOgX74npwyUGFRfg8ha7H9fAjB8ccJCfV971HMUf1JNU/6TI/qaK4FSfZwqArPlR11w9Fd50tetLj6LKH+PNJFCMJ8vc+RF3VUEJH8C4uIHuMyn/7K4vIlVb0qBpwEHADTrFjjNEmIDBJ74RDbDtDLUBAQpAAhCaCSmgmhAmMsJ4QSoEMtHmU9ll7l/fQdc/e56u02Vma4+O+94IdYzS2JJqEFF6CrTJjSlMamfQO956RpmnQKg3TNGXaMEz3khljDIRWKiMfLKN4OoHJpQqmvlZQNio4BcEahAugvAalgIp+ORD2tHKd9kb/BFF7U+G2a8OWf0rlhbWl07NXVvoNJg+Ipm1rPIC1c/Zq0OSGy6vCsxbm97Y492MClLp1GPZ7n7bf/Xmreycb7e9qWD8rBvZUe6IDi7/2Uc/xyVpGrGzOz7Q7LR8tP390Wbxm+XWfrVnKys9MW6WF1KGrQw3L3bU7b3/j+9csIqlt1Luo7XcA7D9VHFzxz+A7shuzqw==

RNG Seed: 3268214518

Trying to cast {SpellID: 58704} but GCD on cooldown for 1s, curTime = 6.686387945s
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xd9020, 0x181d5d0})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x20c24d0, 0x19b3900)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x20c24d0, 0x19b3900)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims/wotlk/sim...

**Comment by rosenrusinov** [comment] 2023-05-16 09:21
Duplicate of #3085

**Closed by rosenrusinov** 2023-05-16 09:21 UTC
