### ISSUE TITLE
Improved Scorch/Winter's Chill Dramatically Reduces DPS

### ISSUE THREAD

**Issue by DylanHolmesDH** [wowsims/wotlk#2419] opened 2023-01-17 16:57 UTC
**Describe the bug**
When using the Warlock simulation if I enabled Improved Scorch under Spell Crit category, it drops my DPS by about 2000+.

**To Reproduce**
1. Go to Settings>Spell Crit>Enable Improved Scorch (or Winters chill).
2. Make sure no Improved Shadow bolt is not enabled.
3. Re-sim and see the DPS drop dramatically.

**Expected behavior**
I would expect to see the DPS increase some amount (the same amount you would expect from enabling Improved shadow bolt)
Disabling all Spell crit does not even drop my DPS by 2000, so the setting is actively stealing DPS not just not applying the 5% crit.
**Sim Links and Screenshots**
[If applicable, add links to your sim settings or screenshots to help explain your problem.
](https://wowsims.github.io/wotlk/warlock/#eJzjUuBgEmCyYHRg8mBcwHiBfwUj4wFGxguMjDcYGV8wMv5gZHIS4mCUYDRgdGBMYCxg7GBkBCoRAuqQ2svaxMgWkJNYmVrEwSrAIbWRkYtf4OluJok3skpsRw8xfd7BxMUp8PUOkxLzLSCTR+AFUO6RrBLzPjDv6XUmiS5ZiBy/wHOg3A+gPqAcSB+vwAug9BwhJRagAAOQ+wQoP0UGyuUU+LiHCWIOu8CHPUwS7bJAxjsgY5oMF4vA+d1MQLJ/H4j8AGbv3wVSeQZoxi9ZIPfaNpDggm1MSoIcjAbcFowBLBGsCYwVIN8tYjrLxDWDiWEUYAVCBqTqqOLhYBRgimCawci4gZExS4KLT4BZglGBSQOYpiyAqU6KDSjPIsHYxahuZGxqYGBgZGAMJIxNDQ2MTEECxsaGhqaGurqmIEkDA1PDR4wSHHPbmQVuPmWSuPyUSaHpMpPGv0tMBo2XmV4wsnxg5J7FKMQlwMXC8Ww1sxAHxBUiDp3QOFVxuMXIMIuJQekrEydEJNNBEKZIctZMEDhpbwkRuWCvmAYG1+yNjjIVzKmt4glILEnOKE8tylYwMlUIluDQonFi+dDoQA1jGk4eocQcAwutAkdSNYEDsWHaIweozhf2wAwWhDd/bbl8d/rVOSftN24Ttkjc+tAeIvrBHibvOF/wr37+Dvs/ke33Q3bet3cSfqceK/zcHpd5Qw2Qnr8A2tGfzg==)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 108

**Comment by Tharre** [comment] 2023-01-17 17:24
This is caused by the rotation code not casting corruption because it's checking for shadow mastery only; will be fixed with the rotation code rework.

**Closed** 2023-01-28 17:36 UTC
Labels: Warlock
