### ISSUE TITLE
Custom rotations for mages no matter the talent tree

### ISSUE THREAD

**Issue by PoicoKronk** [wowsims/wotlk#1591] opened 2022-11-04 15:44 UTC
I like to be able to make custom rotations on everything, I can't really make an arcane mage that's using FFB as primary. 

I would like to be able to create a semi custom rotation. For exemple the arcane rotation is cool but I would like to be able to select my primary (eg. FFB here with arcane missile on procs and PoM + Pyro on CD). Thanks

I would learn how to do it myself but I'm way too far and don't have much time atm :D

I know I'm a bit of a mad scientist when it comes to talent trees and I like to be able to sim everything. Thing is usually what I do is a bit weird so it's not something that's accounted for when these kind of tools are created which I'm not mad about but I really would like to see what It can do. 
Many thanks

**Comment by PANDAxBEARS** [comment] 2022-11-04 19:35
You're free to fork the repo and define whatever mage rotation you'd like here: https://github.com/wowsims/wotlk/blob/master/sim/mage/rotations.go

**Comment by AOSXX** [comment] 2022-11-05 10:18
@PoicoKronk 
As a Le Wagon student and a future alumni, you should maybe try to do it by yourself. 

Also it could be a good idea to pitch this as your project idea ? 
Maybe you could freshen up the website, making it a bit more user friendly. I'm pretty sure you could do a good job.

**Comment by jimmyt857** [comment] 2022-12-15 23:13
Marking as duplicate of #2173 because it's not worth taking the time to implement this individually.

**Closed by jimmyt857** 2022-12-15 23:13 UTC
Labels: Mage
