### ISSUE TITLE
Crash Report -1373683254

### ISSUE THREAD

**Issue by krulbane** [wowsims/wotlk#2695] opened 2023-02-20 20:32 UTC
Link:
http://localhost:3333/wotlk/deathknight/#eJztUz9oE2EUv/d6bS+fip8hw3k05bwpBApf7ppBRL7TRcdYlw4OdrA4OIibdYliHXQoimga8Q/GoZOLIIeoVOtg0GqGxIqTtppeKNIgiEH89+4uBQeLLcTNH8fjft97v/d+3L2PmRpyTMFhyANMAXgA0wAVAB+gBVhB3K2ZlHdhGOKK8az7FPTkjowcP3SMdMx4BGwzL/moN5JWz90ZfDGLLMZfL6LVdd9DtpHfmEf9bTJivfwMsS9JklwnSYsk18pID9vEp+uoj/dbKtUpRK9S4cW+No3xfL3dkJSUWSZlw8Oo5wU6uNTHVH5vESkuvQ9jPYwvAwvnadaUsWLod6bycw/R0jQUkFOHu24iuS+g8h9/RFysVzGmaqDjV9jBkgUATku0F3IwEubcCZd27Wmwa2gYWyJBU5qQ3qD9XAEIOAvpAccWYtDJCmfQtoUjMrYjhHCcjMg42QEilHZElsI86NqVKvLLVdQ/fkCzUMVUoYZisoY+qE3oLYLKkClvQCmiYi1gLBybH3XbBhLu1uJkgLLcHp1U5LbREK+kfQfN/Xp3+h+vSPOk24k2+fKTjvRZD6Jv9mDZ3RXxljwIQ+GlmvmcOjDxOObOlY7uZHMLcq0do7/RkJG+toquKb3+8aV93g85FL74MtJ9l7eCcSVfJm7veTeW+LTq3BNhwek1++oU4mL2eQDNjZx++6uDXxQLwpk=

RNG Seed: 1799059461

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 290 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x65
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:59 +0x9e
panic({0xf67320, 0x3701b90})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x207
github.com/wowsims/wotlk/sim/core.(*Spell).Cast(...)
	/home/runner/work/wotlk/wotlk/sim/core/spell.go:451
github.com/wowsims/wotlk/sim/deathknight/dps.(*DpsDeathknight).RotationActionCallback_Frost_FS_HB(0xc000c80280?, 0xc000e47bd8?, 0x3?, 0xc0006a16e0)
	/home/runner/work/wotlk/wotlk/sim/deathknight/dps/rotation_frost.go:172 +0x53
github.com/wowsims/wotlk/sim/deathknight

**Comment by rosenrusinov** [comment] 2023-02-28 11:37
Duplicate of #2664

**Closed by rosenrusinov** 2023-02-28 11:37 UTC
Labels: Death Knight
