### ISSUE TITLE
Crash Report 698131955 

### ISSUE THREAD

**Issue by emircrnkic** [wowsims/wotlk#4054] opened 2023-11-19 19:17 UTC
Link:
https://wowsims.github.io/wotlk/deathknight/#eJztVV1oHFUUnnPvbDpz2tKbm6SdXJOyDrXG1S0zO91aBZmxL4pPsX0TX4q0iPoQGkGMCFsxxTRC7K9mUcRW/IVEitZNKaVNFVpoIJRNS8QHY8Ru8MG1NQ9Wrd57Z6Yk0tgWq08elt3z833nfPfMZRYzHVAC2EA84Ia4gi9BQ+czm5/fss3KMBRTgMtYdR91ZtrdhsMnyfAIQZt9uYO6VLlL2GcD1PmmPY1m+6mzW0ZnZcTZMcn7tNW1Ze2s/uBSNi0RvStdU0aGDCuSvrctCZex9/fRFD6sWxyX8B/bXTtOnPtDDRmqE2d/m0tnKkrL12Uaz7PZVH/imqy/rr4//E5LlDI+EKnEXTWio6MVhRj5mbj0FYADZJbgcWL8b//IuHezjB7jMvjYZhEGETwMnfAawCcAFYBTAONA6gCisTHG1kMHspAzPNgJ+XxQ8LwgKHrSCvlC4PmBF3gyDAp+0ZdJX/p+4AeBDL8Fx3qrStj+KnHKVZIdqJKOwQnivTFBamDWYXEZHGxA0/r+Y6p+2dsniI4Pl+gomTQdE5vREirT9wtxLVXL+143NiXZU3XqLsIM0vz6bmxJkq+PytuMMp331xSvYtmeIyTB+t3cFOR+g7sii8tzzZbJracU8/MhqqBIgm7d6dcxylcJdx7mvTkYKcjavoNmgd8mWnGpuxjtQ6BAl/pMXdypi4Hw8U5xR1qUh0Mnt9zKcPujNCG0sqIXz5Xr4GvEPaj0zSE15Rrnk8gjRno03iKa5mB1m/FL10yXxwgvCA9X81W4wm3BpkPAuMWoAy5hZrxVtNWuLgOxQHMmpwnfICJcx9di5qJKL0zlOWYBz+wmxKJCngrBSx8WXyJQL+bCsFpMGsVrkr5IdPJWsSLe54F50i/0Un6vKOLd/K70VPJi/AU590GkxO2v0qv95f34CowyMSaTF8/qyH2H2totbY2SW782ai0PKjsd3hdnxsPbt2o7FxZ+Il1vvthjd25+9oknn9uy7ensJsfK/csvso6+6Fa0KZ3+4jp9Nv1d3Vuf63rwVui4lulNl/hUNAjx8kfCZFYt3Kj/Kk7Odjw+MGpH5w92PYDnp8Mb7Ry3mwlj/sQCvHpYWdn7w6OVK+FG7dTCmPd7+K4ad7AWNg89NNXTfHHBuS9owMs3rOu/Nu6NnVFmRfGJfruu0sdu+s/lT5NBLAc=

RNG Seed: 658913863

{SpellID: 48265} failed to cast: still on cooldown for 1s, curTime = 4s
Stack Trace:
goroutine 41 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:123 +0x10
panic({0xe1e60, 0x2a583b0})
	/opt/hostedtoolcache/go/1.21.3/x64/src/runtime...

**Comment by Shaklor** [comment] 2023-11-19 21:20
Setting the fight presence to Unholy doesn’t give the error. Looks like this is where the issue is.

**Comment by jimmyt857** [comment] 2023-12-06 04:33
Looks like a bug with the legacy rotation. Marking wontfix because it will be deprecated soon.

**Comment by jimmyt857** [comment] 2024-01-15 17:28
Closing this because legacy rotations have now been removed.

**Closed by jimmyt857** 2024-01-15 17:28 UTC
Labels: wontfix, Death Knight
