### ISSUE TITLE
Hemo/Backstab available for Sub rogue sims

### ISSUE THREAD

**Issue by BigBadHoss** [wowsims/wotlk#1685] opened 2022-11-13 16:27 UTC
I love using the sim to check weird builds and see how it might work. I noticed that the sim for Sub rogue is casting sinister strike, along with using 3 combo point finishing moves. Which does not appear to be the proper rotation from what information I have been able to find. It would be cool if there was a feature added that allows the user to adjust the rotation more precisely. This would help users that enjoy to check new specs that may also lead to a change in rotation. A feature that would make this great is something similar to weakauras. Allowing for conditions to be met and select an ability to be used during that condition. However, if this is not possible then maybe just improving the sub rogue sim, specifically the rotation, to ensure more accurate dps that is shown.

**Comment by jimmyt857** [comment] 2022-12-15 23:12
Marking this as a duplicate of #2173, as we'll probably want to just build fully-customizable rotations rather than oneoff logic to support this usecase.

**Closed by jimmyt857** 2022-12-15 23:12 UTC
Labels: duplicate, Rogue
