### ISSUE TITLE
Suggest gems crashes the whole desktop wowsim

### ISSUE THREAD

**Issue by Paxtor37** [wowsims/wotlk#3659] opened 2023-09-11 11:26 UTC
I downloaded the desktop version of the program.
When I click on the suggest gems button - does not matter if it's the feral or warrior, the whole program crashes.

**Sim Links and Screenshots**
Attached below are screenshot of error I get before the whole thing crashes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome
 - Version: [v0.1.46](https://github.com/wowsims/wotlk/releases/tag/v0.1.46)

![firefox_1kPUR81NeL](https://github.com/wowsims/wotlk/assets/57117419/a6926887-0f23-45d7-b2d2-84bf74cefcdd)
![firefox_H44av2slBB](https://github.com/wowsims/wotlk/assets/57117419/8d15f714-5ee6-494e-86b7-701613cc2bc4)
![firefox_IQZ4tNtlyo](https://github.com/wowsims/wotlk/assets/57117419/693783b9-f816-4551-a01b-9cebd8782969)

**Comment by netmm** [comment] 2023-09-11 17:28
happened to me at random times but only rarely on the previous version. now it happens every time you press the suggest gem button

**Comment by dlmservers** [comment] 2023-09-11 18:55
happening with stat weights too, everytime

**Comment by jarveson** [comment] 2023-09-11 20:25
cant reproduce this, post a link `export -> link` otherwise #3663 may fix it but could only get a stat weights crash

**Comment by Paxtor37** [comment] 2023-09-11 20:32
[Link to sim, but happens in any, no matter what set I'm editing](http://localhost:3333/wotlk/feral_druid/#eJztU01oE0EUnvd2s9kuDY4lhzUmcV08VGlhdpeAHsJOvbTHqBcRhHqwJw/FU+1pWwiIN0Gl5iS2QkHowZ9QD/5gLTXQQCiYoqdoi6n00BBqzUGps7sBrwajJ7/DMN/3zftheE87rCLDk5DDURgHD2AeoAJQA9gCOB1XwUAeGvcCbxGgjySmlWlQclcuXbt8VVUoJN6DFqOlFupfUqZcXEKi9dCHe2hKT5+hptFl4dRSJhDxqlJH/XbSlIXj0xVhtVJtSmmziXo+bUYFbSs3v6F+K/lLidHNJppREnLxoLaB+k4qVKr7qB2g34VyJ2kqQigG9V/sob4f1O+l85vBXfIdmVbr/rn92Q+ri9rllKkUwzAijCe7aMbEB8Vy8nl5Aq4D3MevqL1C8h9/hD7WacRkVAUdxRA+ggHtmIoU9IgB/ZAlxOM8MpKeAfkiIW+HPEg/gPLqajYhU9uAG3B8MJNxbGZbju3YNrMYyziWOB3mWCxjWYM2czKCWfYn0NXdci+dEzOy/BKNwjvsX1lDtrSGWyA3QCoAeY3kA5ACEnMDe4LOvDF+MOwxzg8V7voouadCpeIeHQtQde3HaJzTIydm/u7wNKZ4N9J4pTddydMJwj97vsOHQt5yR+FssG5OAIkfyW+fWUxLXe6s4cYXhj9OxmW+Pjue1daBjwi2MPzDnfPpLOFB2Xy36/47tNfNY/x3Iy50vKA/AUpyqp4=)

**Comment by jarveson** [comment] 2023-09-11 20:55
ok was able to trigger it a few times just spamming the button. crash points to same issue as stat weights. should be fixed with #3663 as well, wasnt able to trigger after, if it still happens after we'll need locks around backend db access

**Comment by raimondi1337** [comment] 2023-09-12 08:48
Also happening with calculate stat weights, server just closes immediately no errors

**Closed** 2023-09-12 19:22 UTC
