### ISSUE TITLE
Crash Report 1639692181

### ISSUE THREAD

**Issue by TommyMccormick** [wowsims/wotlk#2739] opened 2023-03-04 06:03 UTC
Link:
https://wowsims.github.io/wotlk/tank_deathknight/#eJztVE1oE0EUznuJyWZsdboUncY2XfdUCoVJQg4VZFYv3qStFw8ierAoeKietKe0INUeLBaVNtBWVKoiFFGQFLT4h7TFQIW0Fk+mITH+5xLMSZ39SUlBi6X15rfLzpv3vve92XmzSxoVpMjxOHRBDOA2wBxAHqAEOIcYQ9i7gwIDDTgYknLeoeA7wBLALpfqCoz4esHbdvLo2WOnFT8lgXtAttLiI2TjQd178zmOjSHx0L6PSHy0J4ss0yCNwSlkV+olcTyPLF2neyXLJBI6KiP9QR1c0v6RRna53rT9tJRG3b2QQJnzXYp/bdC90wmUt1S7JXOu1ssqF6fMWvdzSKro2CIuU6podhYrEp68R9YXJC5J7p9CvVrx8Oo290H3GfMNr2MSyRC6/uO3UPlaM7q9CjDUoBe3E6KAfaCaIOD32/FWox+aOY9GeLglwqMtYR7lEXlFOY+ErWckxENyCEkjGloCpnzJIh1NIRtMoTaUwqaBFPLhecyDpwC+OBSBMOJRJpOgUrtGQVjDtU6DaDKSu+tW2YpIbL9hjcZhi2Een1UYAbJFubBN+1kGqEqZS6jMHplExyOzLM+lJFZwmFnhKTqrq1SWXOVhzF3BNdf7MrbKems6LSyIBMBb2Fxj80pC88bRpWfQ2eYThhOpNeriwyZmRKvtmRM7yxrhB6gdYJua//EHUOgxNkImNvNiQ3TWAnvPHn8z9tjzkjgCHdYvo/Hcp/ZEcF5ELGTsRpUbtg4kgqbwhDi1m7y50ZUVn9tNz2uR7q6d2JeeFR0WYXo5/icdu+t3xMr5B1Huva235MxzYuBZsenQwNK616/y5CsTivG3Gb8At1jqiQ==

RNG Seed: 1127147084

runtime error: invalid memory address or nil pointer dereference
Stack Trace:
goroutine 9 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:60 +0x10
panic({0xf6f20, 0x13dcf50})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/deathknight.(*Deathknight).registerSummonGargoyleCD.func1(0x22693f0, 0x232a000, 0x21c1440)
	/home/runner/work/wotlk/wotlk/sim/deathknight/summon_gargoyle.go:38 +0x4
github.com/wowsims/wotlk/sim/core.(*Spell).applyEffects(0x21c1440, 0x22693f0, 0x232a000)
	/home/runner/work/wotlk/wotlk/sim/core

**Comment by rosenrusinov** [comment] 2023-03-09 23:08
Duplicate of #2743

**Closed by rosenrusinov** 2023-03-09 23:08 UTC
Labels: Death Knight Tank
