### ISSUE TITLE
Crash Report -1494707206

### ISSUE THREAD

**Issue by saimpot** [wowsims/wotlk#3939] opened 2023-10-22 16:35 UTC
Link:
http://localhost:3333/wotlk/deathknight/#eJztVV1sFFUU3nNmusxcrDtcaJleW7MOLda1W2d2XKyEZAbjg5iYbGhMCA9CNfiLWlkSlUSziDRtJUpQarsRY4iR+lNpNAHaF7BRLA+bNKYgGB8EVFo0dGFVEDR4Z2ZnO5gKNmjigyebzTnn+87vnp0huoQK1oOOKVwGK6EVn4EMQC9AP+AegH0AIwCHAcYAzgGOIN7RoEIUdWgCG+4CNwbcmHaAzQBvucE8rBehH4GGWKb8BQinVrc8u2qNVKYQdhRIRDl+HtXxGi382RB+MYBEVtryqAmOeo3yHccu1GjCTtc6nEf1bI2HRZSTHDvH4w5dRAcuV86eQnXj9ZrI4RA3xzn+WnXRjCjZCdRkrvOPQ6fK5nZBnajRZG594vkiyt42Qe2q1sJFkqx8nRW8erKytbOoisq73zrfL+XdFn9BtZf5LfZMTFqiMvATalRCvbwJUuJK9HezHX9Gsg9D/8tVCdWnG7GOSKBiLxB+mufBIiq/eFDd6005F9sPwA99GIDNk72IW+1ZnpK3+K1DjPMXF5PZnRCPmwldN82kziURT5i6Yeqmzk0zYSQN7jS4bpiGaXLzGKjStlFUsqOodo1itHsU67sPot5zEMdAzEM4C9WEkWuljsroRV+ASl65WnsIB8OqSOYQiYWJKO3PCJpEuBZfoKdL3o5fcQrvcN7nGtxbUfS+PiRoMplByuJGYzJNRYYLQ1RjUVIZmyOJVHrUIe3+UHDIBM20G3QhJ9Bapl3CeSfA4WWk9W1CFOh1rIqUazOJ/BE4pEKH6IKdLljBZvvArowbLQ3kgJrMIDeyugBE1FilVEbl90pc3jARkrrXzvfvC7SRNRCn7UDQ7NisS4Pw7pDDV14dRLqILSQ6bQzy3T63u+ZIgT8dYooEtGwLooSMVyNguNWyOaQxVk+qKQuOtvtl0Y92ajlTntjpTEmYt+ktbcJUEzvp6tg8MjdWMdkt53rLXJAOZHqSPU5a6Aoyn9X+JT04QZKZ7uYEKg+W1u9uzrkAJ4PIEXSQvk2il0FPB36gBNP/bjF3lq1Tj8jh0ha4j1axucFl+7QTGwWqssqEf7BHjuPk6dLbWJLcTG/yc/Mb/1OO4I/hp1y/SShV5pf+FYSyGNK6heI/+xG7KtvjyAHrds8zYt3woCuHrMRpbH3juXVyqmXtAw8/vWrNY9FmVYr9y4/s+g77n0iTOfDpFfI0Xw7Xm2Ktiy+DX5W4m87Qo3YPeMsfsIq1xqyl7ktxuPn5D47tmGG/+fmGPct2/WBNt0Lf/ffcEhr/xoKl/U/VHcmV4tX7Tib3LzllpeZ3t4sbCtYrT8SXF+pOW7m31R/79oK94uOOF+Uvz0y73n9NqP574aE7V9870440nFnbtei3K060fNqv0T8Al4xjhw==

RNG Seed: 357998342

{SpellID: 48265} failed to cast: still on cooldown for 1s, curTime = 4s
Stack Trace:
goroutine 897 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.1/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/wowsims/wotlk/sim...

**Comment by jimmyt857** [comment] 2023-12-06 05:12
Duplicate of #4054

**Closed by jimmyt857** 2023-12-06 05:12 UTC
Labels: Death Knight
