### ISSUE TITLE
Crash Report -791784348

### ISSUE THREAD

**Issue by Koziyak** [wowsims/wotlk#3089] opened 2023-05-15 14:53 UTC
Link:
https://wowsims.github.io/wotlk/enhancement_shaman/#eJztVE1oE1EQ3plsN8nD2jXk8AxJjXsKYuFtlkB7kLd6UW9pvRTxoAeLgofqQbQXY7VYFFSkCuZoD3rqUYK2oE0upVQ0BwsKYhKqDa00FapJreDsrj8QD1JsD4If+z32zXwz83Z2eCwUAAGdcAB64RxkAG4C7MM0hLATItPaIGjpU8fOHz8TQN0feQSsTb9cRV6NGdrDPOZzyFT9QQXZFv3LPPK3McP3gmx+fXgO+e0oqb+SuU7qZzO4Sh6mX68gH2o3QGGtep2cI1FDJY9C2uUKGkGKL+dcbZs+8g75EgVTndH3TtqnJeR3olRzsuRUzo476+KEs66VHMGlMvKZGB1nuOK8eMdR9cHHaGgBFNCr3sMVZE9Q+Y+/QkisN2JAC4AOHG7BWXaCMdr4OMbpn+gQ2c0w4CMiUSUCsYWoEVuJQSIjbiX6EyB8XW5K+4K9133pv28f9Kp02Wma5JOe9YodYTS4VDQOCbwKPSJlCUuYqaRoQodjTwnLMmkVpmVZImmalvOIlNnRLP+FMvDA9Bzq4wXk+QLG14qYaBRRrBZxHqAGahaUV6BkUTGu+YLusTJ99jbvsGF7e/augynpfZDyXO7sc/FSJl9j/BBv2bXJs1q7aG9EmsxUYUPybAa83k4sfR8WpS6PQo97C3jdX5an97DZ0f6G/BExtr80EB77/HMfdg0fZVNiZcfQQneu/YP09LNN/pr04j7JRVINLVRlfiVx5MZkQzq77tyb3/L9awgJahv1Lmx7HQD7TxGH131vfAOqE72/

RNG Seed: 4193543585

Trying to cast {SpellID: 58704} but GCD on cooldown for 1s, curTime = 6.330850233s
Stack Trace:
goroutine 8 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/debug/stack.go:24 +0x6
github.com/wowsims/wotlk/sim/core.runSim.func1()
	/home/runner/work/wotlk/wotlk/sim/core/sim.go:61 +0x10
panic({0xd90a0, 0x181de00})
	/opt/hostedtoolcache/go/1.18.10/x64/src/runtime/panic.go:838 +0x29
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncGCD.func2(0x20a6370, 0x19b3900)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:204 +0x3f
github.com/wowsims/wotlk/sim/core.(*Spell).wrapCastFuncHaste.func1(0x20a6370, 0x19b3900)
	/home/runner/work/wotlk/wotlk/sim/core/cast.go:183 +0x15
github.com/wowsims/wotlk/sim...

**Comment by rosenrusinov** [comment] 2023-05-16 09:19
Duplicate of #3085

**Closed by rosenrusinov** 2023-05-16 09:19 UTC
Labels: bug, Shaman (Enhancement)
