### ISSUE TITLE
When equipping a staff or polearm in fury warrior offhand it dramatically lowers SIM compared to mace/sword/axe.

### ISSUE THREAD

**Issue by romelthela** [wowsims/wotlk#1642] opened 2022-11-08 16:57 UTC
**Describe the bug**
When equipping a offhand polearm or staff it lowers the parse by ~300 DPS compared to the same Ilvl sword/mace/axe.  Cryptfiends bite for example parses 350 less DPS than Armageddon in my current SIM despite the actually difference likely being somewhere in the range of ~25 given how similar the items are.

**To Reproduce**

**Expected behavior**

**Sim Links and Screenshots**
If applicable, add links to your sim settings or screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hillerstorm** [comment] 2022-11-08 21:53
This is actually a known bug with Whirlwind I think? Where it doesn't actually hit with your off-hand if it's a Staff or Polearm.
So the sim is working as intended for now until that bug gets fixed (if it ever does).

**Comment by TheGroxEmpire** [comment] 2022-11-09 02:43
Correct, this is an intended bug. Closing this issue.

**Closed by TheGroxEmpire** 2022-11-09 02:43 UTC
