### ISSUE TITLE
Crash Report 1898239146

### ISSUE THREAD

**Issue by Jooooooooooooooooo** [wowsims/wotlk#1355] opened 2022-10-18 09:43 UTC
Link:
https://wowsims.github.io/wotlk/raid/#eJztmm9QFOcdx/d5dg+W5U8eqdX13mRzTRvK9Dq7e7kZ7Zs7De3QNs5QnTZMp9NKFA0pgkVsEl4pMY1iE512TNVUcUxsX1inbbQM3B0ggjWogAGFABGMEaTjn+Cfzjg2if39nt09Du6kjInpC+8Hu+w+z7PP6u3nvr8/zyp9P1OqVeUVVzXJKKgor9QKikqLVpSUyYRJ7mNEYeyVRqp2DlFPyuFWWltLFYm1hqmSyTZB++5h6hF771JFZgNhqg4cFOGCl6GjfRAugNG99VRJZ2fqqLoNhhJByWIboXvXDdEjvVtPBRjeBZ2b/yJ6UuAcfmGq12DEyAG8x37oGzsoesSdDXjj15twfwCOM1jt+9YdrJ6L+/DCnfBvOD2IR6fhaNMw9rzcRD2yLOmZBWKhmLuNCkmbZFXCCZKreNyaQuUU2GTY0mCjsImwpcJGYHNlC26qijUkx6v7dd1v+Pymrhs+02cYPjDD9JmG1w8nuqkb0OW7QFT5XC9lv22h6t9HqDbWTXMudVN9pJuOEWmcpO4iabNWcusN1BMyAHjckoDDRaXl5Su0vDVrtbwfymlMcbcgh6N9VO1CDutaKSKXxm5/APRF6hGUqxGqHh+yT2UWClG1HkCAqyI2jHvaKfZlsRpAow1apAjyl8XGYEQfMCaN4nkG6w1Zo+EXrr8CvaMHoAVGW3NvbeRMwv37++wbSmwLp/BICPeXu3DYEbjN+b2iIkDLVpjyEZnqmfNJgVQovUg2EZJEMc6qhDsEMAwSQE2dZbWNBzSSmy7fdYzUkFzTBwSaut+nA2U+HRHUcQMkDa8Xek1TxyEWgpdGKDvUS9UrgOCOMzRnx1mq7zwbRVBA7LrEaqIsKi6q0PIq1pWskGVG3N+GR5f4R2J7PiSw/2OIOOf/IB6FZaqp+iMFGcto8tnGWZXQTbzKLNlkRCUa+SZvVPcH4VHPUWKfr/3cnwzWkEe9fh0fL4qMaRr4wA0THrHu9+NzNy4Q4Z5CchAcmvy9ivK1lY6ItE0Vkc6O6UWkJ3wfIhKJERE4niIi9vUTIiKxfx1KrB+fNlB1GPTDOkIlSerIDA115OdKcAch+8jjtjsjMS4N3ZzLdm0SbFlBkk9+ZV07HniJ/93UGpxehb7BVQgcodcHzs7vAyT9XHfAEXJdsvQIFejNM5T94QxVr06jQJ+g48t7Rvtx2XPlpS85zEYSMSuxTw99TlzfDCfA1fZ5MhsNcVzhFruc+MvycrGsvv72BKvdtq+T2YGIw+onp5KszsCQ1VxFQVVECgvQ97mj1KFUTuHOy3l70ofs6SZ6O9RI7u1MA0My3fBjXAZBmW7htxvwA+envnHmnvhlC8r+rygfcQaLV5drzxRVlJYv/6XsYrI7hAyOwBPuQAaPHaWd9aib/0bdfKsBKRmDzhMI4nUuoyPA68A7otXL2KWwTSP0dnIax2BAN9LYZNF40aGRn6ex6xGYq5NDPQ48VR/Do2sRRzG7wkjeVp4LjPPj5hCOOAXTHB/E89463O+tox5FJjoBAl2FriR8cVYlPD8H2BMRsxz4oIC9FEj8XCrqmxfEzOR+FpQNHa9P5zE/j7L8HD/dbyJg/RBh7X5VVAdPUq26h+Z8BkH+hp4JwDbbH/yCICrdCaTsqfLVzxZVakvKV60rllNZijuMlB2KJPTOzRyrOkfumqNyh/lmJhu05Y53ZLGzdbbWNSNN6eyc7ZoJovVayB7H2OU+2ynDqTXl9joHsRoucbsiuL/SiPtz/TiiGW56iieY

**Comment by lologarithm** [comment] 2022-10-31 22:37
cant reproduce this with just this link. Closing for now

**Closed by lologarithm** 2022-10-31 22:37 UTC
Labels: Raid Sim
